### ISSUE TITLE
log.Fatal() 会崩溃

### ISSUE THREAD

**Issue by airystar** [phuslu/log#1]
请运行这个：
`package main
import "github.com/phuslu/log"
func main() {
	log.Fatal().Str("foo", "bar").Int("number", 42).Msg("a structured logger")
}`
or https://play.golang.org/p/mapv1Ferz8T
tks

**Comment by phuslu** [comment]
嗯，设计 fatal 的确是打印堆栈并退出哎。

**Comment by phuslu** [comment]
标准库也是这个行为呀 https://godoc.org/log#Fatal
