### ISSUE TITLE
RingbufferWriter is needed

### ISSUE THREAD

**Issue by phuslu** [phuslu/log#11]
Currently, ringbuffer implementation in golang is not good enough, we should introduce a ringbuffer writer from scratch.

1. https://github.com/pltr/onering/
1. https://github.com/rs/zerolog/tree/master/diode/
1. https://github.com/smartystreets-prototypes/go-disruptor

**Comment by phuslu** [comment]
a draft committed https://github.com/phuslu/log/blob/master/ring.go

**Comment by phuslu** [comment]
performance benchmark is not good enough, close

**Comment by xenking** [comment]
Maybe this would be useful https://github.com/wait-free/ringbuffer
Or this https://github.com/Workiva/go-datastructures/blob/master/queue/ring.go

**Comment by phuslu** [comment]
close this issue for no plan in current.
