### ISSUE TITLE
对于FileWriter类型的输出，如何支持自定义格式？

### ISSUE THREAD

**Issue by moshuqi** [phuslu/log#18]
作者你好，貌似对于ConsoleWriter类型才有Formatter方法，若我想在输出文件时也自定义格式，要怎么弄？谢谢

**Comment by phuslu** [comment]
构造 ConsoleWriter 时候指定其 Writer 为某个 &FileWriter{} 就可以了。

不过这个在高性能程序的时候不推荐这么用，因为 Formatter 有序列化和反序列化的消耗，比直接写 FileWriter 慢。

**Comment by phuslu** [comment]
我测试过这种用法，在这种场景下，和 zap 差不多快，比 logrus 快一倍多。比 zerolog 快四倍。

原因在这里的第二节解释了： https://github.com/phuslu/log/blob/master/README_zh.md#%E7%A0%B4%E7%BB%BD

**Comment by moshuqi** [comment]
了解了，非常感谢！
