### ISSUE TITLE
MultiWriter panic with AsyncWriter

### ISSUE THREAD

**Issue by xenking** [phuslu/log#23]
Description: Got panic when trying to print messages on Logger with MultiWriter: AsyncWriter in ErrorWriter, InfoWriter, WarnWriter struct fields, and ConsoleWriter. 
Reproduction example: https://play.golang.org/p/gkNrfO2M0Jv

**Comment by phuslu** [comment]
Thanks for figure out, after initial investigation, I think it's a design bug(or miss usage?)
1. async writer will recycle(return to memory pool) when log entry is written.
2. so when multi writer try to write a *recycled* entry to console writer, panic happened.

The workaround is that dont use async writer as a underlying writer, it should use as a *top* writer.

I know this is not very make sense, so I call it may be "design bug", I'm considering a better way to implement async writer
1. fix this problem
2. dont hit performance

**Comment by xenking** [comment]
Tried to [fix](https://github.com/xenking/log/commit/488ea78df503392fe20e43ba64b7d920da1c6aab) without performance downgrades. Can you check?

**Comment by phuslu** [comment]
I afraid that this fix will not 0-allocs for aysnc writer common cases, e.g. https://github.com/phuslu/log#asyncwriter
