### ISSUE TITLE
Docs request: clarification of optimization techniques

### ISSUE THREAD

**Issue by flowchartsman** [phuslu/log#24]
I would be interested in a blurb in the documentation somewhere on the techniques you've chosen to go with which provide this library with its performance over the others which you benchmark against. Often there is a tradeoff in terms of functionality or complexity when enhancing speed over alternatives.  Alternatively, if there are no such concerns, and it's simply clever engineering, that's worth mentioning too, since it would help users contextualize their choice of this library over the alternatives.

**Comment by phuslu** [comment]
Sure and will, this lib used same tricks as zerolog/zap does.
But below tricks is a little rare.
1. unrolled time formatting https://github.com/phuslu/log/blob/master/logger.go#L312
2. Fewly nested functions (also see logger.go), prevent function call overhead

**Comment by phuslu** [comment]
Added. Although not very detailed, but I think code speaks itself.

Anyone who doubt it, fact checking is very welcome. please feedback.
