### ISSUE TITLE
Add golangci-lint

### ISSUE THREAD

**Issue by Juneezee** [phuslu/log#28]
There is some issues in running `golangci-lint` on this project. I am getting the same error output on my local machine as the [job logs](https://github.com/phuslu/log/runs/1872133629).

I have created [an issue in golangci/golangci-lint](https://github.com/golangci/golangci-lint/issues/1730). For now, let's wait until the issue gets resolved, then we add `golangci-lint` again.

**Comment by phuslu** [comment]
thank you so much!
base on your issue, I workaround on https://github.com/phuslu/log/commit/54f3df79f03887f7b716f2d5b08b4640c91e150f and enables go linter
