### ISSUE TITLE
Msg() truncate strings with single quotes when having a custom Formatter

### ISSUE THREAD

**Issue by silisium** [phuslu/log#30]
given a simple Formatter like this :
```go
Formatter: func (w io.Writer, a *log.FormatterArgs) (int, error) {
			return fmt.Fprintf(w, "%s", a.Message)
```
this :
```go
log.Info().Msg("aaaa 'b' cccc")
```
will output :
```
aaaa '
```

**Comment by phuslu** [comment]
thanks for reporting. seems there's a bug in formatter.go json parser

**Comment by phuslu** [comment]
should fixed in https://github.com/phuslu/log/releases/tag/v1.0.68

**Comment by silisium** [comment]
fix confirmed,
thanks for the quick fix, and for this great module
