### ISSUE TITLE
 it does not rotate if you have a TimeFormat defines and a MaxSize then reach MaxSize with the same TimeFormat

### ISSUE THREAD

**Issue by ogimenezb** [phuslu/log#36]
I would like to comment or expand `FileWriter` so we can al better understand it.

- Files are saved according to `name.timestamp.ext`.
- File is always created with the defined or default `TimeFormat`.
- Once program is initiated it only autorotates when condition for `MaxSize` is meet and has a different name.
- If the filename is the same it never autorotates (Should this be like this?)
- If `TimeFormat` is default and goes by minutes each minute it generates a new log file. (Should it be like this?)
- There is no way to compres. (Maybe we can implement it or add `AfterRotate` func for user to do what he wants)

I thinks this deserves a thought to see if it marches what people usually expect.

When rotating if file exists and `MaxSize` is meet we should append `_n`
Don't know how to go about file name... if it does not meet `MaxSize` should we use the same name whether it takes 30m or 30 days and only add timestamp on rotate?

**Comment by phuslu** [comment]
when i decide to chose <symlink> -> filename.<timestamp> implementation, append `_n` suffix is not in my thoughts.

1. use symlink solution is friendly for log collector (firebeat, etc.) 
2. `_n` solution usually cause file renamed maybe cause system pressure.

So I suggest that if you have concern about MaxSize rotation, please use second unit (e.g. '20060102150405') for `TimeFormat`

**Comment by ogimenezb** [comment]
Hi,

I think many things have changed but in essence the problem is that if you have a `TimeFormat`  defines and a `MaxSize` if you reach `MaxSize` with the same `TimeFormat` it does not rotate.

I will retest with new changes and if I see anything I will reopen. Hopefully it's already OK.

Thanks for all your efforts.

**Comment by phuslu** [comment]
reopen it because it really exists, although I think it's a by-designed feature/limitation/bug, like https://github.com/phuslu/log/issues/49 said , and I don't like to add `_n` suffix for fixing.  

But it's better to let this issue keep open.

**Comment by phuslu** [comment]
Added a new notes of issue in https://github.com/phuslu/log#filewriter

**Comment by phuslu** [comment]
finally, I think this is not an issue, just a by-design feature/limitation. thanks.

**Comment by ogimenezb** [comment]
This is a by-design feature/limitation, let me put an example of production logs and propose an option.

I have a long running service with a daily  `TimeFormat` because it's daily only when the `MaxSize` is reached and the `TimeFormat` is different it will autorotate. Sometime, like now, I can see logs from today from the log file created a month ago.  Sometimes I can see the log file go above the `MaxSize` until it rotates. 
So far so good, sometime can be confusing, but everything is consisten.

Here come the exception.
The same long running service has also some commands that are executed by cron. These are executed daily. Here is the inconsistency. Will describe a real case.
I iníciate the service on the first, towards the end of the month I will see the logs from day 1 to 31 in the log file from the first day 01-01-2022, But because I have a daily task I can see 31 files created, each with the cron logs info.
So I end up with 31 files 01-01-2022.....31-01-2022, each with the daily log and the first from the 01-01-2022 with all the logs from the long running service.
That's a problem when trying to find some error. 
Additionally because of  `MaxBackups` the log oldest log, the one from the first day, containing all the long running logs will be deleted. So if I don't catch it on time I will lose information.

Maybe we can create an option that is `RotateOnTimeFormatChange` which will be false by default to keep compatibility and you can set it to true to force a check on `TimeFormat`.

I think this would solve the problem. What are your thoughts?
