### ISSUE TITLE
[QUESTION] - How to use graylog with this library

### ISSUE THREAD

**Issue by sujit-baniya** [phuslu/log#43]
I'm trying to use Graylog as writer. Instead of logging as individual field log is printed as single string field.

Graylog library: https://github.com/Graylog2/go-gelf

How would I implement it for graylog

![image](https://user-images.githubusercontent.com/4959215/123993333-10a9ba00-d9ec-11eb-9204-880c09dca3e0.png)

The code I'm using is this

```go
gelfWriter, err := gelf.NewUDPWriter(grayLogAddr)
	if err != nil {
		panic(err)
	}
	log.DefaultLogger = log.Logger{
		Level:      log.InfoLevel,
		Caller:     0,
		TimeField:  "date",
		TimeFormat: "2006-01-02 15:04:05",
		Writer:     &log.IOWriter{gelfWriter},
	}
r := Request{
			requestId: rid,
			method:    c.Method(),
			host:      c.Hostname(),
			path:      c.Path(),
			request:   string(payload),
			response:  string(response),
			status:    c.Response().StatusCode(),
			latency:   fmt.Sprintf("%s", time.Since(start)),
		}
		log.Info().EmbedObject(&r).Msg("")
```

**Comment by sujit-baniya** [comment]
I see that it requires custom function to be implemented for log. Can you please suggest how I can define custom writer with custom function.

```go
gelfWriter.WriteMessage(&gelf.Message{
			Short:    "Detect URL",
			Full:     "Detect URL",
			TimeUnix: float64(time.Now().Unix()),
			Level:    1,
			Extra:    ToMap(r),
		})
```
Works instead of 
```go
gelfWriter.Write(byteData) // it prints string
```

**Comment by sujit-baniya** [comment]
Any suggestions?

**Comment by phuslu** [comment]
Not sure about this, but maybe can have a look https://github.com/phuslu/log#contextual-fields

**Comment by phuslu** [comment]
I think https://github.com/phuslu/log#user-defined-data-structure could help
