### ISSUE TITLE
Long filename in `caller`

### ISSUE THREAD

**Issue by u2386** [phuslu/log#45]
It would be much convenient if we could log long filename and line number, and stdlib supports this.

**Comment by u2386** [comment]
#44

**Comment by phuslu** [comment]
thanks, merged and renamed the option to `FullpathCaller`

**Comment by phuslu** [comment]
Removed "FullpathCaller" because its name is really untidy.
Now merge it to "Caller".

Set "Caller": 1 will have a short filename caller, set "Caller": -1 will have a long filename caller.

Thanks!
