### ISSUE TITLE
如何把所有日志放一个文件 

### ISSUE THREAD

**Issue by nameliba** [phuslu/log#49]
`log.DefaultLogger.Writer = &log.MultiEntryWriter{

		&log.FileWriter{
			Filename:  "main.log",
			MaxSize:   100 << 20,
			LocalTime: true,
		},
	}`
每次启动会生一个新的"main.2021-10-11T10-32-41.log" 类似的文件，如何控制，都写在同一个文件下，而不是新生成。

**Comment by phuslu** [comment]
可以尝试用 TimeFormat 参数指定时间戳。

![image](https://user-images.githubusercontent.com/195836/137665590-91445f15-ba72-4c12-961c-9f585c4dcb47.png)

比如指定到以天为单位，或者以年为单位。

**Comment by nameliba** [comment]
感谢，真是个巧妙的设计。
