### ISSUE TITLE
How about supporting global level?

### ISSUE THREAD

**Issue by MisLink** [phuslu/log#52]
Setting level to a specific logger is not very useful, normally we want to change level for all created logger. There is no way to do it currently.

**Comment by phuslu** [comment]
no plan.
i think log.DefaultLogger.SetLevel(l) is enough for most users.

let us keep eyes on this issue, if needed, let me add a .SetLevelRef(p *Level) to this lib.

**Comment by MisLink** [comment]
Here is my use case: We have a client program which its logger level can be changed by remote for debugging. It contains many modules (we call them plugins) own the copy of logger with the `Context` marked the plugin.

**Comment by phuslu** [comment]
Got it, let expose a global method, `log.SetLevelForAllLoggers(l)`, it use atomic change a hidden global unit32 inside this lib, then all logger `slient()` method will respect it.

Make sense?

**Comment by MisLink** [comment]
Sounds great. Actually, I implement it in the same way: #53

**Comment by phuslu** [comment]
thanks! Will look today.

**Comment by phuslu** [comment]
In consideration of performance, let me close this request for now, until we could find a better way. thanks again!
