### ISSUE TITLE
FileWriter comment mentions MaxAge but that field does not exist

### ISSUE THREAD

**Issue by cgrinds** [phuslu/log#56]
The comment for `FileWriter` mentions `MaxAge` but that field does not exist.

> Any files with an encoded timestamp older than MaxAge days are deleted, regardless of MaxBackups

`MaxAge` would be nice to have if this library is meant to be a drop-in replacement for Lumberjack.

**Comment by phuslu** [comment]
Oh, I removed the comments now.
I think "MaxAge" is a wrong design for log libs, I recommend that way https://github.com/phuslu/log#rotating-file-writer
