### ISSUE TITLE
Gzip examples writes truncated file

### ISSUE THREAD

**Issue by cgrinds** [phuslu/log#57]
Following the example in #19 

```go
async := &log.AsyncWriter{
    ChannelSize: 1,
    Writer: log.IOWriter{
        Writer: gzip.NewWriter(&log.FileWriter{
            Filename:   "foo.log.gz",
            MaxSize:    50 * 1024 * 1024,
            MaxBackups: 7,
        }),
    },
}
logger := log.Logger{
    Writer: async,
}
logger.Info().Msg("hello phuslu")
async.Close()
```

```bash
ls -la
total 40
-rw-r--r--  1 cgrindst  staff    10B May 20 11:07 foo.log.2022-05-20T15-07-25.gz
lrwxr-xr-x  1 cgrindst  staff    30B May 20 11:07 foo.log.gz@ -> foo.log.2022-05-20T15-07-25.gz

file foo.log.2022-05-20T15-07-25.gz 
foo.log.2022-05-20T15-07-25.gz: gzip compressed data, truncated

gunzip foo.log.2022-05-20T15-07-25.gz 
gunzip: foo.log.2022-05-20T15-07-25.gz: unexpected end of file
gunzip: foo.log.2022-05-20T15-07-25.gz: uncompress failed
```

**Comment by phuslu** [comment]
Oh, AsyncWriter is not well tested, let me give a look.

**Comment by phuslu** [comment]
try a quick fix at master https://github.com/phuslu/log/commit/522857ba2f232b43ddbbc5f4246c194432984256
could you please give a verification? thanks!

**Comment by phuslu** [comment]
Oh, this commit will close os.Stderr in tests, let me try to give another fix.

**Comment by phuslu** [comment]
seems I cannot fixed IOWriter without side effects, so I added a io.WriteCloser,
```go
async := &log.AsyncWriter{
    ChannelSize: 1,
    Writer: log.IOWriteCloser{
        Writer: gzip.NewWriter(&log.FileWriter{
            Filename:   "foo.log.gz",
            MaxSize:    50 * 1024 * 1024,
            MaxBackups: 7,
        }),
    },
}
logger := log.Logger{
    Writer: async,
}
logger.Info().Msg("hello phuslu")
async.Close()
```

could you please try above code? thanks

**Comment by cgrinds** [comment]
thanks for the quick reply @phuslu 

Using your latest fixes the issues. 👍

**Comment by phuslu** [comment]
I think your case

```go
gzip.NewWriter(&log.FileWriter{
            Filename:   "foo.log.gz",
            MaxSize:    50 * 1024 * 1024,
            MaxBackups: 7,
        }
```
is misuse. Because the FileWriter will rotate at your unexpected time.

So the proper way is using gzip.NewWriter + os.File

**Comment by phuslu** [comment]
So as you see, compression + rotation is hard

The most popular way is compress after rotation (nginx,lumberjack, etc...), In this lib,you can provide the `Cleaner` callback to FileWriter for similar thing.

But, please aware this will cause peak pressure to system. Thanks.

**Comment by cgrinds** [comment]
Thanks @phuslu. `gzip.NewWriter + os.File` works. 

Might be worth updating the README examples with that one or maybe you're saying that gziping doesn't belong in your lib, similar to your comment about `MaxAge`? That's probably worth highlighting if so. 

I understand the appeal of keeping your core fast and simple and letting others handle the details of compression, rolling, deletion, etc. 

I'll try using phuslu with [lumberjack](https://github.com/natefinch/lumberjack) as the last writer instead of implementing a `Cleaner` adding `Cron`, etc. I think lumberjack handles all of that and `MaxAge` already and looks like `v3` will round off some rough edges.

**Comment by phuslu** [comment]
thanks. 

I added an example at https://github.com/phuslu/log#rotating-file-writer-with-compression to demo the "compress after rotation" with this lib.
It is more complicated than using lumberjack directly, but it's doable :)

**Comment by cgrinds** [comment]
thanks!
