### ISSUE TITLE
[FEATURE REQUEST] - Hide and/or remove PII data from logging

### ISSUE THREAD

**Issue by sujit-baniya** [phuslu/log#58]
## Description

struct or map might contain PII data and look for an option to hide(mask) such PII data and/or remove such keys

**Comment by phuslu** [comment]
something like https://go.dev/play/p/SoQdwQOaQR2 ?

**Comment by sujit-baniya** [comment]
@phuslu Yes, for Struct, we could use something like that. For map, how would we do that?
