### ISSUE TITLE
gin logger documentation: what is ginlogger.Config?

### ISSUE THREAD

**Issue by nictuku** [phuslu/log#67]
The documentation for the gin logger mentions this:

```
	// Custom logger
	r.Use(ginlogger.SetLogger(ginlogger.Config{
		Logger: &log.Logger{
			Writer: &log.FileWriter{
				Filename: "access.log",
				MaxSize:  1024 * 1024 * 1024,
			},
		},
		Context: log.NewContext(nil).Str("foo", "bar").Value(),
		Skip:    func(c *gin.Context) bool {
			if c.Request.URL.Path == "/backdoor" {
				return true
			}
			return false
		},
	}))
```

What is `ginlogger.Config` ?

The documentation mentioned is at:

https://github.com/phuslu/log-contrib/tree/master/gin

**Comment by phuslu** [comment]
sorry. readme is corrected, thanks.

https://github.com/phuslu/log-contrib/tree/master/gin

**Comment by nictuku** [comment]
Thanks!
________________________________
De: Phus Lu ***@***.***>
Enviado: Sunday, May 5, 2024 6:29:17 AM
Para: phuslu/log ***@***.***>
Cc: nictuku ***@***.***>; Author ***@***.***>
Assunto: Re: [phuslu/log] gin logger documentation: what is ginlogger.Config? (Issue #67)


sorry. readme is corrected, thanks.

https://github.com/phuslu/log-contrib/tree/master/gin
