### ISSUE TITLE
Callers - vary stack depth

### ISSUE THREAD

**Issue by fireflycons** [phuslu/log#68]
Hi @phuslu 

I have a case where I'm wrapping logger inside another abstraction, and I want caller to log the point at which the abstraction is called, rather than `Info()` etc.

How about making the `Caller` member actually by the number of stack frames to look back instead of just a switch?
e.g. 2/-2 would look one frame further. Is there a better way than simply overloading the meaning of `Caller`? For instance a new property in case existing users are relying on `Caller` simply being not zero and not explicitly 1/-1

I could look into it

**Comment by phuslu** [comment]
Emmm, this is a bit intentional, because I dont like introduce too many fields into Logger struct -- the more fields, the more mental burden.

So `Caller` a pretender/metaphor for `CallerEnabled+CallerDepth+CallerFullPath`.

For "developer" rather "users", I think using minus/plus operation on `Caller` is just fine. E.g. https://github.com/phuslu/log-contrib/blob/master/logr/logr.go#L9-L29

**Comment by fireflycons** [comment]
Is that actually doing what I think it is? `Caller=3` will look down 3 frames?
That's what I was initially suggesting, but if it already works that way, then there's nothing to do!

**Comment by phuslu** [comment]
> Caller=3 will look down 3 frames
Yes, it's a bit obscure, I did intend to implement it this way.

**Comment by phuslu** [comment]
BTW, to minimalized the "Caller" overhead, I manually inlined(aka copy&paste) the runtime.callers code to each level. https://github.com/phuslu/log/blob/master/logger.go#L112-L174

Finnally, the logger has performance advantages in this benchmark.
```
goos: linux
goarch: amd64
cpu: AMD EPYC 7763 64-Core Processor

BenchmarkCallerZap-4          	 5967156	      2016 ns/op	     440 B/op	       3 allocs/op
BenchmarkCallerZeroLog-4      	 9310912	      1286 ns/op	     304 B/op	       4 allocs/op
BenchmarkCallerPhusLog-4      	17120493	       705.3 ns/op	     232 B/op	       2 allocs/op

PASS
ok  	command-line-arguments	194.383s
```

**Comment by phuslu** [comment]
>  there's no way to persuade the compiler to inline it if it were a function

Almost yes. only some tricks can be used https://dave.cheney.net/2020/05/02/mid-stack-inlining-in-go

**Comment by phuslu** [comment]
I tweaking `Caller` again, now its performance is good enough. 😆 

https://github.com/phuslu/log/actions/runs/8809631070/job/24180742047
```
BenchmarkCallerZap
BenchmarkCallerZap-4          	 5791486	      2052 ns/op	     440 B/op	       3 allocs/op
BenchmarkCallerZeroLog
BenchmarkCallerZeroLog-4      	 9236912	      1297 ns/op	     304 B/op	       4 allocs/op
BenchmarkCallerPhusLog
BenchmarkCallerPhusLog-4      	243238	       498.2 ns/op	       0 B/op	       0 allocs/op
```

**Comment by phuslu** [comment]
I tagged v1.0.91 for releasing this improvement, thanks for enquiry/advice  to make it better!
