### ISSUE TITLE
[FEATURE REQUEST] - Add support for function With to predefine parameters for logger

### ISSUE THREAD

**Issue by sujit-baniya** [phuslu/log#73]
Logging same multiple parameters in various places, we have to repeat the parameters in multiple places. It would be really helpful if the package supports some function that allows to predefine the parameters and use the logger.

For example

```go
logger := logger.With().Str("attr1", "1").Str("clientID","123")
logger.Info().Msg("This is test")
```

This would print log with provided parameters

```json
{"attr1": "1", "clientID": "123", "msg": "This is test"}
```

**Comment by phuslu** [comment]
I through this idioms so long and finally I give up to implement it -- because this API model is memory wasting.

But I developed an alternative method as below
```go
logger := logger
logger.Context = log.NewContext(nil).Str("attr1", "1").Str("clientID","123").Value()
logger.Info().Msg("This is test")
```

**Comment by sujit-baniya** [comment]
Makes sense

```go
package main

import (
	"github.com/oarkflow/log"
)

func main() {
	logger := log.NewContext(log.DefaultLogger.Context).Str("attr1", "12").Copy()
	logger.Info().Str("foo", "bar").Int("number", 42).Msg("hi, phuslog")
	logger.Info().Msgf("foo=%s number=%d error=%+v", "bar", 42, "an error")
}
```

Any thoughts on such API model?

Here, I guess `DefaultLogger.Context` will have Level data as well. So I'm not sure how to deal with Level

**Comment by sujit-baniya** [comment]
Example:

```go
func (e *Entry) Copy() *Logger {
	return &Logger{
		Context: e.buf,
		Writer:  e.w,
	}
}
```

**Comment by phuslu** [comment]
Yes, it can.

But I can also provide another memory-effective example in real world 😄 

1. define a request-scope struct and managed by sync.Pool, it contains to explicit `LogContext Context` field   https://github.com/phuslu/liner/blob/master/handler_http.go#L34-L66
2. set value to `LogConext` with memory-recycling, the `NewContext(ri.LogContext[:0])` casting magic https://github.com/phuslu/liner/blob/master/handler_http.go#L100-L116 
3. call `log.Context(ri.LogContext).` explicitly to logging with context https://github.com/phuslu/liner/blob/master/handler_http_web_index.go#L55

As we see, it a bit more troublesome than `With` idioms, but it's truely 0-allocs and archives to highest performance.

That's all why I designed/implemented such API mode.
