### ISSUE TITLE
w.vwriter undefined (type *AsyncWriter has no field or method vwriter

### ISSUE THREAD

**Issue by pankajsoni19** [phuslu/log#75]
/../../../../go/pkg/mod/github.com/phuslu/log@v1.0.103/async.go:52:9: w.vwriter undefined (type *AsyncWriter has no field or method vwriter) (exit status 1)

Getting this go version 1.22

**Comment by phuslu** [comment]
it's a bit wired. what's is your environment, is it some special linux (e.g. wsl1) ?

**Comment by phuslu** [comment]
fixed in v1.0.104 please check, sorry again.

v1.0.103 brings the automatic `writev` support to AsyncWriter with a obviously improvement, but it lacks a placeholder for other platform, now it fixed, thanks for this.
