### ISSUE TITLE
Plans for supporting Unstructured Logging

### ISSUE THREAD

**Issue by LutherLee** [phuslu/log#76]
May I know if there are plans to support unstructured logging with async support?

**Comment by phuslu** [comment]
I tried (let AsyncWriter to be an io.Writer) but the initial implementation is a bit dirty.

Let me consider it again in later days, thanks.

**Comment by phuslu** [comment]
Just now I committed a standalone io.Writer support in https://github.com/phuslu/log/blob/master/async_file.go

Although it's a bit repeatable, but I think it more clean than impalement it in original  AsyncWriter.

You can have a try `go get github.com/phuslu/log@master` if you want, I will continue the tweaking.
