### ISSUE TITLE
封装 syscall.writev 处理 syscall.EINTR

### ISSUE THREAD

**Issue by xuyang2** [phuslu/log#78]
将 `FileWriter.WriteV()` 中的直接调用 `syscall.Syscall(syscall.SYS_WRITEV, ...)` 提取成方法，处理 syscall.EINTR

https://github.com/phuslu/log/blob/3cf00ff432d2862d69b27abf8181f64e1d7160ec/file_linux.go#L19

https://github.com/phuslu/log/blob/3cf00ff432d2862d69b27abf8181f64e1d7160ec/file_linux.go#L35

https://github.com/golang/go/blob/82c371a307116450e9ab4dbce1853da3e69f4061/src/internal/poll/fd_writev_unix.go#L14

**Comment by phuslu** [comment]
谢谢，已经合并并且发布 v1.0.7
