### ISSUE TITLE
初始化失败的 Windows EventlogWriter 多次调用 WriteEntry 会 panic

### ISSUE THREAD

**Issue by xuyang2** [phuslu/log#83]
设置不当（或者 RegisterEventSourceW 失败）的 Windows EventlogWriter 多次调用 WriteEntry 会 panic

版本:
v1.0.107 5101934b9fc25de50ca1a2c40af8f7b2414f5b24

复现:
```
func TestEventlogWriter_WriteEntry(t *testing.T) {
	t.Run("test init err", func(t *testing.T) {
		w := &EventlogWriter{
			Source: "",
			ID:     0, // trigger init err
		}
		if _, err := w.WriteEntry(&Entry{Level: InfoLevel, buf: []byte("foo")}); err == nil {
			t.Errorf("expect init err, got nil")
		}
		if _, err := w.WriteEntry(&Entry{Level: InfoLevel, buf: []byte("bar")}); err == nil { // panic: runtime error: invalid memory address or nil pointer dereference
			t.Errorf("expect init err, got nil")
		}
	})
}
```

相关代码:
https://github.com/phuslu/log/blob/212b9f977c4ab27485aa643d179aec60cc305480/eventlog.go#L41-L67

原因:
`w.once.Do(func() { ... })` 第二次执行时，第二个闭包不会执行，也不会自动把第一次执行时的第一个闭包的副作用应用过来

**Comment by phuslu** [comment]
让我尝试使用 double lock checking 来解决一下。

**Comment by xuyang2** [comment]
`syscall.StringToUTF16Ptr` 出错会 panic 
建议换用返回 error 的 `syscall.UTF16PtrFromString`

https://github.com/golang/go/blob/go1.18/src/syscall/syscall_windows.go#L90

**Comment by phuslu** [comment]
谢谢，已经改了推送了。
