### ISSUE TITLE
FileWriter.TimeFormat的值为空时会生成两个日志文件

### ISSUE THREAD

**Issue by dxvgef** [phuslu/log#85]
```
FileWriter{
	Filename:   "main.log",
	TimeFormat: "",
}
```
当`TimeFormat`的值为空时，会生成一个main.log和一个默认时间格式的log文件，总共两个，是故意这样设计的吗？

**Comment by phuslu** [comment]
是的，我在这里总结过这个动机和优点。

https://github.com/phuslu/log/issues/34#issuecomment-860096423

**Comment by dxvgef** [comment]
明白了，原来main.log是个符号链接，之前我没仔细看，谢谢
