### ISSUE TITLE
建议增加Caller等输出项是否默认输出的配置选项

### ISSUE THREAD

**Issue by bagualing** [phuslu/log#88]
针对Caller、callerfunc等输出项目，建议增加配置选项来控制是否输出这些项目。
比如Caller，可以配置是否默认全局输出，还是只有生成日志条目时，调用了Caller()的条目才输出。

我不知道日前这个库是否已支持上面说的？我没找到，只能通过自已写个Formatter来实现，如果能增加配置项目会更好。

另外v1.0.112版，有两个Warning，反馈一下：
![PixPin_2024-10-18_08-18-21](https://github.com/user-attachments/assets/fadd05d0-8e4e-4239-b864-5798577b2b09)

**Comment by phuslu** [comment]
https://github.com/phuslu/log?tab=readme-ov-file#logger

caller 开关请见上面示例。warning 我看一下，谢谢。

**Comment by bagualing** [comment]
明白了，谢谢！

**Comment by bagualing** [comment]
@phuslu 另外请问 func (w *MultiLevelWriter) WriteEntry(e *Entry) (n int, err error) 这个方法里，
if err1 != nil && err == nil { } 这里的err作为命名返回值，默认不就是nil吗？怎么还要在这里判断一下呢？
